spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: your-256-bit-secret-key-here-make-it-long-and-secure-for-production
  expiration: 3600000 # 1 hour in milliseconds

rate-limit:
  capacity: 100
  time: 1 # 1 second